// Use importScripts to import workbox-sw (will be handled by the build process)
importScripts(
  "https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js"
);

// Use workbox global variable now
workbox.setConfig({
  debug: false,
});

const { precacheAndRoute } = workbox.precaching;
const { registerRoute } = workbox.routing;
const { StaleWhileRevalidate } = workbox.strategies;

// Precache all assets generated by the build process
precacheAndRoute([{"revision":"9901214fd275e474fe5277e6a4769e9d","url":"assets/index-C6ieU8XS.js"},{"revision":"8353e05f0e971d07bea7c61f165ea572","url":"assets/index-C8PAtLOU.css"},{"revision":"a7361c2c5048a7802c8c0c01d7c312f4","url":"index.html"},{"revision":"8e3a10e157f75ada21ab742c022d5430","url":"vite.svg"}]);

// Cache API responses
registerRoute(
  ({ url }) => url.origin === "https://api.thenewsapi.com",
  new StaleWhileRevalidate({
    cacheName: "news-api-cache",
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: "image-cache",
  })
);
