// Use importScripts to import workbox-sw (will be handled by the build process)
importScripts(
  "https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js"
);

// Use workbox global variable now
workbox.setConfig({
  debug: false,
});

const { precacheAndRoute } = workbox.precaching;
const { registerRoute } = workbox.routing;
const { StaleWhileRevalidate } = workbox.strategies;

// Precache all assets generated by the build process
precacheAndRoute([{"revision":"8353e05f0e971d07bea7c61f165ea572","url":"assets/index-C8PAtLOU.css"},{"revision":"949d423da5358ecb371d4667438847b4","url":"assets/index-D2CxB3XQ.js"},{"revision":"b4ae31654db751ec601c5bc12cbce2ce","url":"index.html"},{"revision":"8e3a10e157f75ada21ab742c022d5430","url":"vite.svg"}]);

// Cache API responses
registerRoute(
  ({ url }) => url.origin === "https://api.thenewsapi.com",
  new StaleWhileRevalidate({
    cacheName: "news-api-cache",
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: "image-cache",
  })
);
