// Use importScripts to import workbox-sw (will be handled by the build process)
importScripts(
  "https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js"
);

// Use workbox global variable now
workbox.setConfig({
  debug: false,
});

const { precacheAndRoute } = workbox.precaching;
const { registerRoute } = workbox.routing;
const { StaleWhileRevalidate } = workbox.strategies;

// Get the base URL for GitHub Pages (e.g., "/pwa-news-reader/")
const scope = self.registration.scope;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache API responses
registerRoute(
  ({ url }) => url.origin === "https://api.thenewsapi.com",
  new StaleWhileRevalidate({
    cacheName: "news-api-cache",
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: "image-cache",
  })
);

// Handle navigation requests for SPA
self.addEventListener("fetch", (event) => {
  // Skip non-GET requests
  if (event.request.method !== "GET") return;

  // Handle navigation requests
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request).catch(() => {
        // If fetch fails (offline), return the cached index.html
        return caches.match(scope + "index.html");
      })
    );
  }
});
