// This file is automatically generated during build
export const buildVersion = {
  version: "1.0.0", // Will read from package.json
  timestamp: new Date().toISOString(),
  buildId: Math.random().toString(36).substring(2, 15),
};
